name: Publishing npm package

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Run tests
      run: npm run test

    - name: Prepare package
      run: npm run build-package

    - name: Publish to NPM
      working-directoty: './.build/'
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
